name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: hello-binary
        path: ./hello
