name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04  # Use the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: hello-binary
        path: ./hello

